name: Publish VS Code Extension

on:
  push:
    tags:
      - "v*"

jobs:
  publish-marketplace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Publish to Visual Studio Marketplace
        continue-on-error: true  # This allows the workflow to continue even if marketplace publish fails
        uses: HaaLeo/publish-vscode-extension@v1.6.2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com

  create-release:
    runs-on: ubuntu-latest
    needs: publish-marketplace  # This ensures this job runs after the marketplace publish attempt
    steps:
      - uses: actions/checkout@v4
        
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
